# Generated by Django 4.2.23 on 2025-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_password',
            field=models.CharField(blank=True, help_text='Encrypted or encoded admin password for the site (store securely!)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='installed_apps',
            field=models.TextField(blank=True, help_text='Comma-separated list of installed Frappe apps for this site', null=True),
        ),
    ]
