entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsEncryptDns:
    acme:
      email: taher.badnawarwala@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: godaddy

  letsEncryptHttp:
    acme:
      email: taher.badnawarwala@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
      
