entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt-dns:
    acme:
      email: taher.badnawarwala@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: godaddy
      domains:
        - main: "*.preciseerp.com"
  letsencrypt-http:
    acme:
      email: taher.badnawarwala@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
